### ISSUE TITLE
Where can I find facenet_models?

### ISSUE THREAD

**Issue by AzwadFawadHasan** [blevlabs/Adaptive-Face-Recognition#1]
Traceback (most recent call last):
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\mymain.py", line 1, in <module>
    from face_database import database_initialization
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\face_database.py", line 8, in <module>
    from profiling import Profiling, userinput
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\profiling.py", line 2, in <module>
    from facenet_models import FacenetModel
ModuleNotFoundError: No module named 'facenet_models'

**Comment by blevlabs** [comment]
@AzwadFawadHasan You can find it here: https://github.com/CogWorksBWSI/facenet_models

**Comment by AzwadFawadHasan** [comment]
It solved the issue. But, where can I find the model at? It's giving the error below

C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\Scripts\python.exe C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\mymain.py 
Traceback (most recent call last):
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/kdhht2334/autotrain-diffusion-emotion-facial-expression-recognition-40429105176/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\huggingface_hub\utils\_errors.py", line 293, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64e49eb3-7e964e7d2804620a65d47df1;f5a23999-1739-4d12-b231-1425c371c650)

Repository Not Found for url: https://huggingface.co/kdhht2334/autotrain-diffusion-emotion-facial-expression-recognition-40429105176/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\mymain.py", line 1, in <module>
    from face_database import database_initialization
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\face_database.py", line 16, in <module>
    emotion = EmotionRecognition()
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\adaptiveFaceRecognition\Adaptive-Face-Recognition\emotion.py", line 7, in __init__
    self.model = pipeline("image-classification",
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\pipelines\__init__.py", line 705, in pipeline
    config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 983, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\configuration_utils.py", line 672, in _get_config_dict
    resolved_config_file = cached_file(
  File "C:\Users\dellG15\Documents\pythonProject\chapter8FaceDetection\myNewVenv\lib\site-packages\transformers\utils\hub.py", line 433, in cached_file
    raise EnvironmentError(
OSError: kdhht2334/autotrain-diffusion-emotion-facial-expression-recognition-40429105176 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

Process finished with exit code 1

**Comment by blevlabs** [comment]
@AzwadFawadHasan It looks like the user took down the emotion recognition model. I will look to rehost the model from my HF account and update the repo

**Comment by AzwadFawadHasan** [comment]
@blevlabs  alright thanks. I am trying to see whether it can detect faces from my custom images/ live video. Hopefully it will work better than dlib, deepface etc
